import type { WeaponDefinition, WeaponName } from "../../types";

export const WEAPON_DEFINITIONS = {
  laser: {
    name: "laser",
    visual: "laserBolt",
    muzzleOffsetForward: 2.64,
    muzzleOffsetSide: 1.8,
    fireSound: "laserShot1",
    fireVolumePlayer: 0.65,
    fireVolumeEnemy: 0.4,
    hitSound: "laserHit",
    hitVolumeAgainstAsteroid: 0.65,
    hitVolumeAgainstShip: 0.8,
    hitSoundOffsetSeconds: 0.41,
    hitSoundPlaybackRate: 1.25,
    heat: 33,
    shotsPerSecond: 2,
    speed: 82,
    lifetimeSeconds: 1.2,
    damage: 8,
    radius: 0.41,
    mass: 1.5,
    projectileMass: 0.5,
    visualLength: 2.8,
    visualWidth: 0.3,
  },
  kineticTorpedo: {
    name: "kineticTorpedo",
    visual: "kineticTorpedo",
    muzzleOffsetForward: 2.64,
    muzzleOffsetSide: 2.6,
    hitSound: "explosion2",
    hitVolumeAgainstAsteroid: 0.75,
    hitVolumeAgainstShip: 0.85,
    hitSoundOffsetSeconds: 0.05,
    heat: 50,
    shotsPerSecond: 1.15,
    speed: 85,
    initialSpeed: 10,
    initialSpeedDuration: 0.4,
    thrust: 65,
    lifetimeSeconds: 2.8,
    damage: 20.5,
    radius: 2.15,
    mass: 3,
    projectileMass: 2.0,
    visualLength: 3.2,
    visualWidth: 1.3,
  },
  plasmaOrb: {
    name: "plasmaOrb",
    visual: "plasmaOrb",
    muzzleOffsetForward: 2.64,
    muzzleOffsetSide: 0,
    fireSound: "plasmaOrbShot1",
    fireVolumePlayer: 0.8,
    fireVolumeEnemy: 0.8,
    heat: 45,
    shotsPerSecond: 1.65,
    speed: 68,
    lifetimeSeconds: 1.8,
    damage: 30,
    radius: 0.87,
    mass: 3,
    projectileMass: 5.0,
    visualLength: 1.8,
    visualWidth: 2.43,
  },
  lightPlasmaCannon: {
    name: "lightPlasmaCannon",
    visual: "lightPlasmaCannon",
    muzzleOffsetForward: 2.64,
    muzzleOffsetSide: 0,
    fireVolumePlayer: 0.35,
    fireVolumeEnemy: 0.3,
    hitSound: "plasmaCannonHit",
    hitVolumeAgainstAsteroid: 1.15,
    hitVolumeAgainstShip: 1.2,
    hitSoundOffsetSeconds: 0.55,
    hitSoundPlaybackRate: 1.2,
    hitSoundPlaybackRateMax: 1.4,
    fireSound: "plasmaOrbShot1",
    heat: 52,
    shotsPerSecond: 1.45,
    speed: 62,
    lifetimeSeconds: 1.8,
    damage: 30,
    radius: 3.4,
    mass: 3,
    projectileMass: 5.0,
    visualLength: 1.8,
    visualWidth: 2.43,
  },
} satisfies Record<WeaponName, WeaponDefinition>;

export function getWeaponDefinition(name: WeaponName): WeaponDefinition {
  return WEAPON_DEFINITIONS[name];
}
